// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrderService.Data;

#nullable disable

namespace OrderService.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxStates");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxStates");
                });

            modelBuilder.Entity("OrderService.Models.CustomerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CustomerProfiles");
                });

            modelBuilder.Entity("OrderService.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("integer");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Orders_CreatedAt");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("IX_Orders_CustomerId");

                    b.HasIndex("CustomerName")
                        .HasDatabaseName("IX_Orders_CustomerName");

                    b.HasIndex("CustomerPhone")
                        .HasDatabaseName("IX_Orders_CustomerPhone");

                    b.HasIndex("PaymentMethod")
                        .HasDatabaseName("IX_Orders_PaymentMethod");

                    b.HasIndex("ShippingFee")
                        .HasDatabaseName("IX_Orders_ShippingFee");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Orders_Status");

                    b.HasIndex("CustomerId", "Status", "CreatedAt")
                        .HasDatabaseName("IX_Orders_CustomerId_Status_CreatedAt");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 1, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerName = "Nguyễn Văn An",
                            CustomerPhone = "0901000001",
                            Note = "Giao giờ hành chính",
                            PaymentMethod = 0,
                            ShippingAddress = "123 Lê Lợi, Q1, HCM",
                            ShippingFee = 30000m,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 1, 10, 14, 30, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerName = "Nguyễn Văn An",
                            CustomerPhone = "0901000001",
                            Note = "",
                            PaymentMethod = 1,
                            ShippingAddress = "123 Lê Lợi, Q1, HCM",
                            ShippingFee = 0m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CustomerName = "Trần Thị Bích",
                            CustomerPhone = "0902000002",
                            Note = "Gọi trước khi giao",
                            PaymentMethod = 2,
                            ShippingAddress = "456 Nguyễn Huệ, Q1, HCM",
                            ShippingFee = 15000m,
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2025, 2, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CustomerName = "Trần Thị Bích",
                            CustomerPhone = "0902000002",
                            Note = "",
                            PaymentMethod = 3,
                            ShippingAddress = "789 Cách Mạng Tháng 8, Q3, HCM",
                            ShippingFee = 20000m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2025, 2, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CustomerName = "Lê Hoàng Cường",
                            CustomerPhone = "0903000003",
                            Note = "Hàng dễ vỡ",
                            PaymentMethod = 0,
                            ShippingAddress = "10 Pasteur, Q3, HCM",
                            ShippingFee = 25000m,
                            Status = 4
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2025, 2, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerName = "Nguyễn Văn An",
                            CustomerPhone = "0901000001",
                            Note = "",
                            PaymentMethod = 1,
                            ShippingAddress = "123 Lê Lợi, Q1, HCM",
                            ShippingFee = 0m,
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("a0000007-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2025, 2, 15, 13, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CustomerName = "Lê Hoàng Cường",
                            CustomerPhone = "0903000003",
                            Note = "",
                            PaymentMethod = 2,
                            ShippingAddress = "20 Hai Bà Trưng, Q1, HCM",
                            ShippingFee = 10000m,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a0000008-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2025, 3, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CustomerName = "Trần Thị Bích",
                            CustomerPhone = "0902000002",
                            Note = "Đóng gói kỹ",
                            PaymentMethod = 0,
                            ShippingAddress = "456 Nguyễn Huệ, Q1, HCM",
                            ShippingFee = 30000m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("a0000009-0000-0000-0000-000000000009"),
                            CreatedAt = new DateTime(2025, 3, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerName = "Nguyễn Văn An",
                            CustomerPhone = "0901000001",
                            Note = "",
                            PaymentMethod = 3,
                            ShippingAddress = "123 Lê Lợi, Q1, HCM",
                            ShippingFee = 15000m,
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("a0000010-0000-0000-0000-000000000010"),
                            CreatedAt = new DateTime(2025, 3, 10, 15, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CustomerName = "Lê Hoàng Cường",
                            CustomerPhone = "0903000003",
                            Note = "",
                            PaymentMethod = 1,
                            ShippingAddress = "10 Pasteur, Q3, HCM",
                            ShippingFee = 0m,
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("a0000011-0000-0000-0000-000000000011"),
                            CreatedAt = new DateTime(2025, 3, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CustomerName = "Trần Thị Bích",
                            CustomerPhone = "0902000002",
                            Note = "",
                            PaymentMethod = 0,
                            ShippingAddress = "789 CMT8, Q3, HCM",
                            ShippingFee = 20000m,
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a0000012-0000-0000-0000-000000000012"),
                            CreatedAt = new DateTime(2025, 3, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerName = "Nguyễn Văn An",
                            CustomerPhone = "0901000001",
                            Note = "Giao cuối tuần",
                            PaymentMethod = 2,
                            ShippingAddress = "123 Lê Lợi, Q1, HCM",
                            ShippingFee = 10000m,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("a0000013-0000-0000-0000-000000000013"),
                            CreatedAt = new DateTime(2025, 3, 25, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("33333333-3333-3333-3333-333333333333"),
                            CustomerName = "Lê Hoàng Cường",
                            CustomerPhone = "0903000003",
                            Note = "",
                            PaymentMethod = 3,
                            ShippingAddress = "20 Hai Bà Trưng, Q1, HCM",
                            ShippingFee = 25000m,
                            Status = 4
                        },
                        new
                        {
                            Id = new Guid("a0000014-0000-0000-0000-000000000014"),
                            CreatedAt = new DateTime(2025, 4, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CustomerName = "Trần Thị Bích",
                            CustomerPhone = "0902000002",
                            Note = "",
                            PaymentMethod = 1,
                            ShippingAddress = "456 Nguyễn Huệ, Q1, HCM",
                            ShippingFee = 0m,
                            Status = 3
                        },
                        new
                        {
                            Id = new Guid("a0000015-0000-0000-0000-000000000015"),
                            CreatedAt = new DateTime(2025, 4, 5, 16, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CustomerName = "Nguyễn Văn An",
                            CustomerPhone = "0901000001",
                            Note = "Ưu tiên giao sớm",
                            PaymentMethod = 0,
                            ShippingAddress = "123 Lê Lợi, Q1, HCM",
                            ShippingFee = 30000m,
                            Status = 0
                        });
                });

            modelBuilder.Entity("OrderService.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderItems_OrderId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_OrderItems_ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000001-0000-0000-0000-000000000001"),
                            OrderId = new Guid("a0000001-0000-0000-0000-000000000001"),
                            ProductId = new Guid("c0000001-0000-0000-0000-000000000001"),
                            ProductName = "Áo thun nam",
                            Quantity = 2,
                            UnitCost = 90000m,
                            UnitPrice = 150000m
                        },
                        new
                        {
                            Id = new Guid("b0000002-0000-0000-0000-000000000002"),
                            OrderId = new Guid("a0000001-0000-0000-0000-000000000001"),
                            ProductId = new Guid("c0000002-0000-0000-0000-000000000002"),
                            ProductName = "Quần jean",
                            Quantity = 1,
                            UnitCost = 200000m,
                            UnitPrice = 350000m
                        },
                        new
                        {
                            Id = new Guid("b0000003-0000-0000-0000-000000000003"),
                            OrderId = new Guid("a0000002-0000-0000-0000-000000000002"),
                            ProductId = new Guid("c0000003-0000-0000-0000-000000000003"),
                            ProductName = "Giày thể thao",
                            Quantity = 1,
                            UnitCost = 550000m,
                            UnitPrice = 890000m
                        },
                        new
                        {
                            Id = new Guid("b0000004-0000-0000-0000-000000000004"),
                            OrderId = new Guid("a0000003-0000-0000-0000-000000000003"),
                            ProductId = new Guid("c0000001-0000-0000-0000-000000000001"),
                            ProductName = "Áo thun nam",
                            Quantity = 3,
                            UnitCost = 90000m,
                            UnitPrice = 150000m
                        },
                        new
                        {
                            Id = new Guid("b0000005-0000-0000-0000-000000000005"),
                            OrderId = new Guid("a0000003-0000-0000-0000-000000000003"),
                            ProductId = new Guid("c0000004-0000-0000-0000-000000000004"),
                            ProductName = "Túi xách nữ",
                            Quantity = 1,
                            UnitCost = 300000m,
                            UnitPrice = 520000m
                        },
                        new
                        {
                            Id = new Guid("b0000006-0000-0000-0000-000000000006"),
                            OrderId = new Guid("a0000003-0000-0000-0000-000000000003"),
                            ProductId = new Guid("c0000005-0000-0000-0000-000000000005"),
                            ProductName = "Nón lưỡi trai",
                            Quantity = 2,
                            UnitCost = 50000m,
                            UnitPrice = 95000m
                        },
                        new
                        {
                            Id = new Guid("b0000007-0000-0000-0000-000000000007"),
                            OrderId = new Guid("a0000004-0000-0000-0000-000000000004"),
                            ProductId = new Guid("c0000002-0000-0000-0000-000000000002"),
                            ProductName = "Quần jean",
                            Quantity = 2,
                            UnitCost = 200000m,
                            UnitPrice = 350000m
                        },
                        new
                        {
                            Id = new Guid("b0000008-0000-0000-0000-000000000008"),
                            OrderId = new Guid("a0000005-0000-0000-0000-000000000005"),
                            ProductId = new Guid("c0000003-0000-0000-0000-000000000003"),
                            ProductName = "Giày thể thao",
                            Quantity = 1,
                            UnitCost = 550000m,
                            UnitPrice = 890000m
                        },
                        new
                        {
                            Id = new Guid("b0000009-0000-0000-0000-000000000009"),
                            OrderId = new Guid("a0000005-0000-0000-0000-000000000005"),
                            ProductId = new Guid("c0000005-0000-0000-0000-000000000005"),
                            ProductName = "Nón lưỡi trai",
                            Quantity = 1,
                            UnitCost = 50000m,
                            UnitPrice = 95000m
                        },
                        new
                        {
                            Id = new Guid("b0000010-0000-0000-0000-000000000010"),
                            OrderId = new Guid("a0000006-0000-0000-0000-000000000006"),
                            ProductId = new Guid("c0000004-0000-0000-0000-000000000004"),
                            ProductName = "Túi xách nữ",
                            Quantity = 1,
                            UnitCost = 300000m,
                            UnitPrice = 520000m
                        },
                        new
                        {
                            Id = new Guid("b0000011-0000-0000-0000-000000000011"),
                            OrderId = new Guid("a0000007-0000-0000-0000-000000000007"),
                            ProductId = new Guid("c0000001-0000-0000-0000-000000000001"),
                            ProductName = "Áo thun nam",
                            Quantity = 5,
                            UnitCost = 90000m,
                            UnitPrice = 150000m
                        },
                        new
                        {
                            Id = new Guid("b0000012-0000-0000-0000-000000000012"),
                            OrderId = new Guid("a0000008-0000-0000-0000-000000000008"),
                            ProductId = new Guid("c0000002-0000-0000-0000-000000000002"),
                            ProductName = "Quần jean",
                            Quantity = 1,
                            UnitCost = 200000m,
                            UnitPrice = 350000m
                        },
                        new
                        {
                            Id = new Guid("b0000013-0000-0000-0000-000000000013"),
                            OrderId = new Guid("a0000008-0000-0000-0000-000000000008"),
                            ProductId = new Guid("c0000003-0000-0000-0000-000000000003"),
                            ProductName = "Giày thể thao",
                            Quantity = 1,
                            UnitCost = 550000m,
                            UnitPrice = 890000m
                        },
                        new
                        {
                            Id = new Guid("b0000014-0000-0000-0000-000000000014"),
                            OrderId = new Guid("a0000009-0000-0000-0000-000000000009"),
                            ProductId = new Guid("c0000005-0000-0000-0000-000000000005"),
                            ProductName = "Nón lưỡi trai",
                            Quantity = 3,
                            UnitCost = 50000m,
                            UnitPrice = 95000m
                        },
                        new
                        {
                            Id = new Guid("b0000015-0000-0000-0000-000000000015"),
                            OrderId = new Guid("a0000010-0000-0000-0000-000000000010"),
                            ProductId = new Guid("c0000001-0000-0000-0000-000000000001"),
                            ProductName = "Áo thun nam",
                            Quantity = 1,
                            UnitCost = 90000m,
                            UnitPrice = 150000m
                        },
                        new
                        {
                            Id = new Guid("b0000016-0000-0000-0000-000000000016"),
                            OrderId = new Guid("a0000010-0000-0000-0000-000000000010"),
                            ProductId = new Guid("c0000004-0000-0000-0000-000000000004"),
                            ProductName = "Túi xách nữ",
                            Quantity = 2,
                            UnitCost = 300000m,
                            UnitPrice = 520000m
                        },
                        new
                        {
                            Id = new Guid("b0000017-0000-0000-0000-000000000017"),
                            OrderId = new Guid("a0000011-0000-0000-0000-000000000011"),
                            ProductId = new Guid("c0000002-0000-0000-0000-000000000002"),
                            ProductName = "Quần jean",
                            Quantity = 1,
                            UnitCost = 200000m,
                            UnitPrice = 350000m
                        },
                        new
                        {
                            Id = new Guid("b0000018-0000-0000-0000-000000000018"),
                            OrderId = new Guid("a0000012-0000-0000-0000-000000000012"),
                            ProductId = new Guid("c0000003-0000-0000-0000-000000000003"),
                            ProductName = "Giày thể thao",
                            Quantity = 1,
                            UnitCost = 550000m,
                            UnitPrice = 890000m
                        },
                        new
                        {
                            Id = new Guid("b0000019-0000-0000-0000-000000000019"),
                            OrderId = new Guid("a0000012-0000-0000-0000-000000000012"),
                            ProductId = new Guid("c0000001-0000-0000-0000-000000000001"),
                            ProductName = "Áo thun nam",
                            Quantity = 2,
                            UnitCost = 90000m,
                            UnitPrice = 150000m
                        },
                        new
                        {
                            Id = new Guid("b0000020-0000-0000-0000-000000000020"),
                            OrderId = new Guid("a0000013-0000-0000-0000-000000000013"),
                            ProductId = new Guid("c0000004-0000-0000-0000-000000000004"),
                            ProductName = "Túi xách nữ",
                            Quantity = 1,
                            UnitCost = 300000m,
                            UnitPrice = 520000m
                        },
                        new
                        {
                            Id = new Guid("b0000021-0000-0000-0000-000000000021"),
                            OrderId = new Guid("a0000014-0000-0000-0000-000000000014"),
                            ProductId = new Guid("c0000005-0000-0000-0000-000000000005"),
                            ProductName = "Nón lưỡi trai",
                            Quantity = 4,
                            UnitCost = 50000m,
                            UnitPrice = 95000m
                        },
                        new
                        {
                            Id = new Guid("b0000022-0000-0000-0000-000000000022"),
                            OrderId = new Guid("a0000014-0000-0000-0000-000000000014"),
                            ProductId = new Guid("c0000002-0000-0000-0000-000000000002"),
                            ProductName = "Quần jean",
                            Quantity = 1,
                            UnitCost = 200000m,
                            UnitPrice = 350000m
                        },
                        new
                        {
                            Id = new Guid("b0000023-0000-0000-0000-000000000023"),
                            OrderId = new Guid("a0000015-0000-0000-0000-000000000015"),
                            ProductId = new Guid("c0000001-0000-0000-0000-000000000001"),
                            ProductName = "Áo thun nam",
                            Quantity = 1,
                            UnitCost = 90000m,
                            UnitPrice = 150000m
                        },
                        new
                        {
                            Id = new Guid("b0000024-0000-0000-0000-000000000024"),
                            OrderId = new Guid("a0000015-0000-0000-0000-000000000015"),
                            ProductId = new Guid("c0000003-0000-0000-0000-000000000003"),
                            ProductName = "Giày thể thao",
                            Quantity = 1,
                            UnitCost = 550000m,
                            UnitPrice = 890000m
                        },
                        new
                        {
                            Id = new Guid("b0000025-0000-0000-0000-000000000025"),
                            OrderId = new Guid("a0000015-0000-0000-0000-000000000015"),
                            ProductId = new Guid("c0000004-0000-0000-0000-000000000004"),
                            ProductName = "Túi xách nữ",
                            Quantity = 1,
                            UnitCost = 300000m,
                            UnitPrice = 520000m
                        });
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("OrderService.Models.OrderItem", b =>
                {
                    b.HasOne("OrderService.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OrderService.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
